# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dff4d9ad3d8bfe0f2651e101283686d87cb95e61d619184bc542c2aa25eb39cdd086b50bf830eb46d59e87dd146cdf4b0a4f032a735268c3193110e6889affd5

test:
  secret_key_base: 8da290709950162af7bcc077792e964b8238f432dd666fcf7d9f29381422ca240db27c6e5b8b2df17121ed809828c70f6baecd1a7a1081cb2cab79f2bcc670fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
